[fix] Fix `custom_backend_meta` related issue (#47)
## Description
Running ```TQ_TEST_BACKEND=Yuanrong pytest -s
tests/e2e/test_e2e_lifecycle_consistency.py``` raise error.

## Main Changes
- Fix a bug where `custom_backend_meta` of `extended_meta` was missing
in
```test_e2e_lifecycle_consistency.py::test_cross_shard_complex_update```.
- Fix a bug where `KVStorageManager::put_data` used outdated
`field_names` of metadata.
- Add a preventative parameter checks to `KVStorageManager::put_data`.

## Other Infos
```bash
$ TQ_TEST_BACKEND=Yuanrong pytest -s tests/e2e/test_e2e_lifecycle_consistency.py

========================================================================================== short test summary info ===========================================================================================
FAILED tests/e2e/test_e2e_lifecycle_consistency.py::test_cross_shard_complex_update - RuntimeError: Error in clear operation: No strategy supports item of type NoneType: None. Available strategies: ['NPUTensorKVClientAdapter', 'GeneralKVClientAdapter']
================================================================================== 1 failed, 7 passed, 1 warning in 17.76s ===================================================================================
```
- `clear_partition` still raises error in
```test_e2e_lifecycle_consistency.py::test_cross_shard_complex_update```,
because some keys generated by metadata were not put before.
- We plan to support automatic startup of **Yuanrong** for `tq.init()`.

---------

Signed-off-by: dpj135 <958208521@qq.com>
Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>